name: Build OpenWrt for SEED AC2

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 2 * * 1'  # 每周一凌晨2点自动编译

env:
  OPENWRT_BRANCH: master
  TIME_ZONE: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set timezone
      run: |
        sudo timedatectl set-timezone $TIME_ZONE

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y $(cat scripts/dependencies.txt)
        sudo apt clean

    - name: Checkout OpenWrt source
      run: |
        git clone https://github.com/immortalwrt/immortalwrt.git openwrt
        cd openwrt
        echo "Using default branch: $(git branch --show-current)"

    - name: Apply BeeconMini patches
      run: |
        cd openwrt
        chmod +x ../scripts/apply_patches.sh
        ../scripts/apply_patches.sh

    - name: Verify patches
      run: |
        cd openwrt
        chmod +x ../scripts/verify_patches.sh
        ../scripts/verify_patches.sh

    - name: Configure target
      run: |
        cd openwrt
        make defconfig

    - name: Build firmware
      run: |
        cd openwrt
        make -j$(nproc) V=s

    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware-seed-ac2-master
        path: |
          openwrt/bin/targets/mediatek/filogic/
          openwrt/bin/packages/
        retention-days: 30

    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs-master
        path: |
          openwrt/logs/
        retention-days: 7