# 进入项目目录
cd BeeconMini-SEED-AC-Build

# 创建修复后的工作流文件
cat > .github/workflows/build-openwrt.yml << 'EOF'
name: Build OpenWrt for SEED AC2

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y $(cat scripts/dependencies.txt)

    - name: Checkout OpenWrt source
      run: |
        git clone https://github.com/immortalwrt/immortalwrt.git openwrt
        cd openwrt

    - name: Apply BeeconMini patches
      run: |
        cd openwrt
        chmod +x ../scripts/apply_patches.sh
        ../scripts/apply_patches.sh

    - name: Build firmware
      run: |
        cd openwrt
        make -j$(nproc)

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: seed-ac2-firmware
        path: openwrt/bin/targets/mediatek/filogic/
EOF

# 提交并推送修复
git add .
git commit -m "fix: use github-hosted runner to fix container error"
git push origin main